/**
 * PWA surface: service worker, manifest and icon as ROUTES (audio-feed-4xb).
 *
 * This app has no static-file pipeline — every page is a self-contained document
 * rendered by a route (see home.ts, admin.ts, listen.ts) — so `/sw.js`,
 * `/manifest.json` and the icon are routes too. Dropping files in a `public/` dir
 * would quietly do nothing, which is the kind of "it looks wired" mistake this
 * codebase has been bitten by before.
 *
 * The service worker's strategy, and why:
 *
 * - AUDIO is cache-first. The offline cache is the whole point of the feature, so
 *   a downloaded episode must be served from it without a network round trip, and
 *   the player needs no separate offline mode: the same URL simply resolves.
 * - NAVIGATIONS are network-first, falling back to the cached page. A podcast's
 *   episode list changes; serving a stale shell to an online user would hide new
 *   episodes, while an offline user needs the last good page. Network-first is the
 *   only order that gives both.
 * - The MANIFEST and ICON are cache-first: they change rarely and are needed for
 *   install prompts offline.
 * - Nothing else is intercepted. Caching API responses here would create a second,
 *   invisible source of truth for the episode list and for admin data.
 */
import type { RouteContext } from "../router.ts";
import type { AppContext } from "../app.ts";

/** Must match the cache name the player writes downloads into. */
export const OFFLINE_CACHE = "audio-feed-offline-v1";
export const SHELL_CACHE = "audio-feed-shell-v1";

export const MANIFEST = {
  name: "Audio Feed",
  short_name: "AudioFeed",
  description: "Your RSS articles, read aloud: direct reads and two-voice deep dives.",
  start_url: "/listen",
  scope: "/",
  display: "standalone",
  theme_color: "#18181b",
  background_color: "#09090b",
  icons: [
    { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "maskable" },
  ],
  shortcuts: [{ name: "Listen", url: "/listen" }],
};

/** A dark, rounded podcast mark: concentric "sound" arcs over a filled circle. */
export const ICON_SVG =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Audio Feed">
  <rect width="512" height="512" rx="112" fill="#18181b"/>
  <circle cx="256" cy="256" r="58" fill="#a78bfa"/>
  <g fill="none" stroke="#a78bfa" stroke-width="26" stroke-linecap="round" opacity="0.85">
    <path d="M150 176a150 150 0 0 0 0 160"/>
    <path d="M362 176a150 150 0 0 1 0 160"/>
  </g>
  <g fill="none" stroke="#a78bfa" stroke-width="22" stroke-linecap="round" opacity="0.5">
    <path d="M96 132a190 190 0 0 0 0 248"/>
    <path d="M416 132a190 190 0 0 1 0 248"/>
  </g>
</svg>
`;

const javascript = (body: string, cacheControl: string) =>
  new Response(body, {
    headers: {
      "content-type": "text/javascript; charset=utf-8",
      "cache-control": cacheControl,
      // The worker is served from the root, so its default scope is already "/";
      // the header is explicit so a future move of this route cannot silently
      // narrow the scope to the script's own path.
      "service-worker-allowed": "/",
      "referrer-policy": "no-referrer",
    },
  });

/** `GET /sw.js` — served `no-cache` so a deploy's new worker is actually picked up. */
export function handleServiceWorker(_ctx: RouteContext<AppContext>): Response {
  const body = `/* Audio Feed service worker (audio-feed-4xb). Generated by src/routes/pwa.ts. */
"use strict";
const SHELL_CACHE = ${JSON.stringify(SHELL_CACHE)};
const OFFLINE_CACHE = ${JSON.stringify(OFFLINE_CACHE)};
const PRECACHE = ["/manifest.json", "/icon.svg"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) =>
        Promise.all(
          names
            // Only clean caches this worker owns; the offline audio cache is the
            // subscriber's own downloaded library and must survive an update.
            .filter((name) => name.startsWith("audio-feed-shell-") && name !== SHELL_CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Downloaded audio: serve from cache first, so an offline episode plays from the
  // same URL it streams from when online.
  if (url.pathname.startsWith("/audio/")) {
    event.respondWith(
      (async () => {
        const offline = await caches.open(OFFLINE_CACHE);
        const cached = await offline.match(request);
        if (cached) return cached;
        try {
          return await fetch(request);
        } catch (error) {
          // This handler used to answer EVERY failure with "not downloaded for
          // offline listening", which is a diagnosis it has no evidence for. In
          // production the real fault was a CORS block on a redirect to R2, and
          // this message sent the investigation to the offline cache instead --
          // the thing that WAS working. A fetch() here rejects for any network
          // reason: offline, DNS, TLS, a blocked cross-origin response.
          //
          // So it now reports what it knows (the request failed, and whether the
          // browser believes it is offline) rather than guessing why.
          const offlineNow = typeof navigator !== "undefined" && navigator.onLine === false;
          const detail = String((error && error.message) || error);
          return new Response(
            offlineNow
              ? "You are offline and this episode has not been downloaded. " +
                "Download it while online to listen offline."
              : "Could not load this episode's audio: " + detail +
                ". The episode is not saved on this device, so it needs the network.",
            {
              status: 503,
              headers: {
                "content-type": "text/plain; charset=utf-8",
                "cache-control": "no-store",
              },
            },
          );
        }
      })(),
    );
    return;
  }

  // Navigations: network first so new episodes appear, cache when offline.
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(request);
          if (fresh.ok) {
            const shell = await caches.open(SHELL_CACHE);
            await shell.put(request, fresh.clone());
          }
          return fresh;
        } catch {
          const shell = await caches.open(SHELL_CACHE);
          const cached = (await shell.match(request)) || (await shell.match("/listen"));
          return (
            cached ||
            new Response(
              "<!doctype html><meta charset=utf-8><title>Offline</title>" +
                "<body style=\\"font-family:system-ui;background:#09090b;color:#fafafa;padding:2rem\\">" +
                "<h1>Offline</h1><p>Open this app once while online, then use the Download button " +
                "on an episode to listen offline.</p>",
              { status: 200, headers: { "content-type": "text/html; charset=utf-8" } },
            )
          );
        }
      })(),
    );
    return;
  }

  // Install-critical, rarely changing assets.
  if (url.pathname === "/manifest.json" || url.pathname === "/icon.svg") {
    event.respondWith(
      (async () => {
        const shell = await caches.open(SHELL_CACHE);
        const cached = await shell.match(request);
        if (cached) return cached;
        const fresh = await fetch(request);
        if (fresh.ok) await shell.put(request, fresh.clone());
        return fresh;
      })(),
    );
  }
});

// Background Fetch, all three events (audio-feed-rqp).
//
// audio-feed-4xb wired only the success handler and the page never started a
// fetch, because the API measured as non-functional. Re-measured against a real
// origin it works end to end, and audio-feed-98i carries the correction.
//
// An earlier version of this comment blamed headless Chrome for the original
// finding. That mechanism was wrong and is retracted: headless Chrome 152 on a
// real origin has a service worker and completes a background fetch. The API
// looks broken because getIds() is empty BOTH when nothing registered and when
// a fetch has finished, and because only the first fetch per origin is
// permitted (audio-feed-zlf) — a refused attempt resolves and never lists.
self.addEventListener("backgroundfetchsuccess", (event) => {
  event.waitUntil(
    (async () => {
      const offline = await caches.open(OFFLINE_CACHE);
      const records = await event.registration.matchAll();
      let stored = 0;
      for (const record of records) {
        const response = await record.responseReady;
        if (response && response.ok) {
          await offline.put(record.request, response);
          stored++;
        }
      }
      // The OS notification is the only surface a subscriber sees once the tab is
      // closed, so it states the outcome rather than staying on "downloading".
      if (event.updateUI) {
        await event.updateUI({
          title: stored === 1 ? "Episode ready offline" : stored + " episodes ready offline",
        });
      }
    })(),
  );
});

// A failed or aborted fetch caches NOTHING, deliberately. Background Fetch can
// deliver partial records, and a half-written episode would be indistinguishable
// from a complete one at playback time: the player's whole "is it downloaded?"
// test is the presence of the URL in this cache. A truncated file that plays and
// stops is worse than an absent one the page can retry in the foreground.
self.addEventListener("backgroundfetchfail", (event) => {
  event.waitUntil(
    (async () => {
      if (event.updateUI) {
        await event.updateUI({ title: "Download failed — open Audio Feed to retry" });
      }
    })(),
  );
});

// Tapping the OS download notification belongs in the player, not a new tab: an
// already-open listener is focused rather than duplicated, because two copies of
// this page means two <audio> elements and two media sessions.
self.addEventListener("backgroundfetchclick", (event) => {
  event.waitUntil(
    (async () => {
      const open = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of open) {
        if (client.url.includes("/listen")) return client.focus();
      }
      return self.clients.openWindow("/listen");
    })(),
  );
});
`;
  return javascript(body, "no-cache");
}

/** `GET /manifest.json` — installability metadata. */
export function handleManifest(_ctx: RouteContext<AppContext>): Response {
  return new Response(JSON.stringify(MANIFEST, null, 2) + "\n", {
    headers: {
      "content-type": "application/manifest+json; charset=utf-8",
      "cache-control": "public, max-age=300",
    },
  });
}

/** `GET /icon.svg` — the app icon, as a route so no binary lives in the repo. */
export function handleIcon(_ctx: RouteContext<AppContext>): Response {
  return new Response(ICON_SVG, {
    headers: {
      "content-type": "image/svg+xml; charset=utf-8",
      "cache-control": "public, max-age=86400",
    },
  });
}
